### ISSUE TITLE
commit 04567af7e7ed5060597d317349443725ed0c013f breaks unit test in oslotest

### ISSUE THREAD

**Issue by dims** [testing-cabal/testtools#214]
https://bugs.launchpad.net/oslotest/+bug/1545576

Just run "tox -epy27" in oslotest repo (git://git.openstack.org/openstack/oslotest) to recreate the problem.

**Comment by rbtcollins** [comment]
I think that means that oslotest is either buggy, or the unit test in oslotest is buggy. Depending on leaking state between test case execution isn't something we're going to support. Leaving this open in case its not that.

**Comment by dims** [comment]
@rbtcollins : i know enough to diagnose, not enough to propose a patch either to testtools or oslotest, so please advise what needs to be fixed.

Thanks,
Dims

**Comment by rbtcollins** [comment]
Yah, I've dug into oslotest - there's some entirely questionable code in base.py - overriding __init__. Because its set in __init__, it gets reset when the pre-running code makes the test case clean before running it. Basically this has been broken for running-N-times since forever in oslo, and this improvement in testtools has exposed the breakage. Deleting __init__ from there and moving the other things to (respectively) a class assignment and a setUp call should address it.
