### ISSUE TITLE
Deprecate and drop Python 3.4 support

### ISSUE THREAD

**Issue by mtreinish** [testing-cabal/testtools#279]
Python 3.4 was marked as EoL in March 2019 (https://www.python.org/dev/peps/pep-0429/#id4 ) and has no upstream support anymore. It also accounts for < 1% of our current pypi downloads. We should mark python 3.4 support as deprecated and stop testing it a release or 2 after that deprecation is announced.

**Comment by hugovk** [comment]
I'd like to suggest dropping 3.4 without a deprecation period.

* It's not used much
* It's already 7 months EOL and people should already upgrade to 3.5+
* For those with 3.4, `python_requires` in `setup.py` will tell pip to install the last-supported version, so they will still get a usable version:
```python
    python_requires='>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*',
```
* Python 3.4 is already causing problems for testtools because dependencies have also dropped it meaning the CI fails:
```console
$ pip install sphinx Twisted
DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last one supporting it. Please upgrade your Python as Python 3.4 won't be maintained after March 2019 (cf PEP 429).
Collecting sphinx
  Downloading https://files.pythonhosted.org/packages/7d/66/a4af242b4348b729b9d46ce5db23943ce9bca7da9bbe2ece60dc27f26420/Sphinx-1.8.5-py2.py3-none-any.whl (3.1MB)
Collecting Twisted
  Downloading https://files.pythonhosted.org/packages/0b/95/5fff90cd4093c79759d736e5f7c921c8eb7e5057a70d753cdb4e8e5895d7/Twisted-19.10.0.tar.bz2 (3.1MB)
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-l2cpxb2_/Twisted/setup.py", line 20, in <module>
        setuptools.setup(**_setup["getSetupArgs"]())
      File "<string>", line 258, in getSetupArgs
      File "<string>", line 209, in _checkPythonVersion
    ImportError: Twisted on Python 3 requires Python 3.5 or later.
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-l2cpxb2_/Twisted/
The command "pip install sphinx Twisted" failed and exited with 1 during .
```
* pip has been giving deprecation warnings for 3.4 since before the EOL (see in log above)
* Most projects I've seen drop EOL Python versions after (or sometimes before) the EOL date with no deprecation warning/period. (I still recommend deprecations for standard feature removals.)

Please see PR https://github.com/testing-cabal/testtools/pull/282.
